/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "mbed_rpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mbed_rpc_Header, mbed_rpc_Header, AUTO)


PB_BIND(mbed_rpc_BaseMessage, mbed_rpc_BaseMessage, AUTO)


PB_BIND(mbed_rpc_NullMessage, mbed_rpc_NullMessage, AUTO)


PB_BIND(mbed_rpc_ErrorMessage, mbed_rpc_ErrorMessage, 2)


PB_BIND(mbed_rpc_AckNackMessage, mbed_rpc_AckNackMessage, AUTO)


PB_BIND(mbed_rpc_TickMessage, mbed_rpc_TickMessage, AUTO)


PB_BIND(mbed_rpc_ConsoleMessage, mbed_rpc_ConsoleMessage, AUTO)


PB_BIND(mbed_rpc_SystemInfoMessage, mbed_rpc_SystemInfoMessage, AUTO)


PB_BIND(mbed_rpc_PingMessage, mbed_rpc_PingMessage, AUTO)


PB_BIND(mbed_rpc_NotifyTimeElapsedRequest, mbed_rpc_NotifyTimeElapsedRequest, AUTO)


PB_BIND(mbed_rpc_NotifyTimeElapsedResponse, mbed_rpc_NotifyTimeElapsedResponse, AUTO)


PB_BIND(mbed_rpc_LoggerEraseRequest, mbed_rpc_LoggerEraseRequest, AUTO)


PB_BIND(mbed_rpc_LoggerEraseResponse, mbed_rpc_LoggerEraseResponse, AUTO)


PB_BIND(mbed_rpc_LoggerReadRequest, mbed_rpc_LoggerReadRequest, AUTO)


PB_BIND(mbed_rpc_LoggerReadResponse, mbed_rpc_LoggerReadResponse, AUTO)


PB_BIND(mbed_rpc_LoggerReadStreamResponse, mbed_rpc_LoggerReadStreamResponse, 2)


PB_BIND(mbed_rpc_LoggerWriteRequest, mbed_rpc_LoggerWriteRequest, 2)


PB_BIND(mbed_rpc_LoggerWriteResponse, mbed_rpc_LoggerWriteResponse, AUTO)









