# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mbed_rpc.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mbed_rpc.proto',
  package='mbed.rpc',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0embed_rpc.proto\x12\x08mbed.rpc\x1a\x0cnanopb.proto\"u\n\x06Header\x12\r\n\x05magic\x18\x01 \x02(\r\x12\x14\n\x05msgId\x18\x02 \x02(\rB\x05\x92?\x02\x38\x08\x12\x14\n\x05subId\x18\x03 \x02(\rB\x05\x92?\x02\x38\x08\x12\x14\n\x05seqId\x18\x04 \x02(\rB\x05\x92?\x02\x38\x10\"\x1a\n\tConstants\x12\r\n\x05MAGIC\x10\xcc\xac\xc2\xf0\x01\"/\n\x0b\x42\x61seMessage\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\";\n\x04Ping\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\x12\x11\n\ttimestamp\x18\x02 \x02(\r\"8\n\x14ListFunctionsRequest\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\"L\n\x15ListFunctionsResponse\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\x12\x11\n\tfunctions\x18\x02 \x03(\t*\x19\n\tErrorCode\x12\x0c\n\x08NO_ERROR\x10\x00*\x1f\n\x0f\x42uiltinServices\x12\x0c\n\x08SVC_PING\x10\x00*\x1f\n\x0f\x42uiltinMessages\x12\x0c\n\x08MSG_PING\x10\x00'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='mbed.rpc.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=407,
  serialized_end=432,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
_BUILTINSERVICES = _descriptor.EnumDescriptor(
  name='BuiltinServices',
  full_name='mbed.rpc.BuiltinServices',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SVC_PING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=434,
  serialized_end=465,
)
_sym_db.RegisterEnumDescriptor(_BUILTINSERVICES)

BuiltinServices = enum_type_wrapper.EnumTypeWrapper(_BUILTINSERVICES)
_BUILTINMESSAGES = _descriptor.EnumDescriptor(
  name='BuiltinMessages',
  full_name='mbed.rpc.BuiltinMessages',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MSG_PING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=467,
  serialized_end=498,
)
_sym_db.RegisterEnumDescriptor(_BUILTINMESSAGES)

BuiltinMessages = enum_type_wrapper.EnumTypeWrapper(_BUILTINMESSAGES)
NO_ERROR = 0
SVC_PING = 0
MSG_PING = 0


_HEADER_CONSTANTS = _descriptor.EnumDescriptor(
  name='Constants',
  full_name='mbed.rpc.Header.Constants',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MAGIC', index=0, number=504403532,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=133,
  serialized_end=159,
)
_sym_db.RegisterEnumDescriptor(_HEADER_CONSTANTS)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='mbed.rpc.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='magic', full_name='mbed.rpc.Header.magic', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msgId', full_name='mbed.rpc.Header.msgId', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subId', full_name='mbed.rpc.Header.subId', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seqId', full_name='mbed.rpc.Header.seqId', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HEADER_CONSTANTS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=159,
)


_BASEMESSAGE = _descriptor.Descriptor(
  name='BaseMessage',
  full_name='mbed.rpc.BaseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='mbed.rpc.BaseMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=208,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='mbed.rpc.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='mbed.rpc.Ping.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mbed.rpc.Ping.timestamp', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=269,
)


_LISTFUNCTIONSREQUEST = _descriptor.Descriptor(
  name='ListFunctionsRequest',
  full_name='mbed.rpc.ListFunctionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='mbed.rpc.ListFunctionsRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=327,
)


_LISTFUNCTIONSRESPONSE = _descriptor.Descriptor(
  name='ListFunctionsResponse',
  full_name='mbed.rpc.ListFunctionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='mbed.rpc.ListFunctionsResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='functions', full_name='mbed.rpc.ListFunctionsResponse.functions', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=405,
)

_HEADER_CONSTANTS.containing_type = _HEADER
_BASEMESSAGE.fields_by_name['header'].message_type = _HEADER
_PING.fields_by_name['header'].message_type = _HEADER
_LISTFUNCTIONSREQUEST.fields_by_name['header'].message_type = _HEADER
_LISTFUNCTIONSRESPONSE.fields_by_name['header'].message_type = _HEADER
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['BaseMessage'] = _BASEMESSAGE
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['ListFunctionsRequest'] = _LISTFUNCTIONSREQUEST
DESCRIPTOR.message_types_by_name['ListFunctionsResponse'] = _LISTFUNCTIONSRESPONSE
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
DESCRIPTOR.enum_types_by_name['BuiltinServices'] = _BUILTINSERVICES
DESCRIPTOR.enum_types_by_name['BuiltinMessages'] = _BUILTINMESSAGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'mbed_rpc_pb2'
  # @@protoc_insertion_point(class_scope:mbed.rpc.Header)
  })
_sym_db.RegisterMessage(Header)

BaseMessage = _reflection.GeneratedProtocolMessageType('BaseMessage', (_message.Message,), {
  'DESCRIPTOR' : _BASEMESSAGE,
  '__module__' : 'mbed_rpc_pb2'
  # @@protoc_insertion_point(class_scope:mbed.rpc.BaseMessage)
  })
_sym_db.RegisterMessage(BaseMessage)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'mbed_rpc_pb2'
  # @@protoc_insertion_point(class_scope:mbed.rpc.Ping)
  })
_sym_db.RegisterMessage(Ping)

ListFunctionsRequest = _reflection.GeneratedProtocolMessageType('ListFunctionsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTFUNCTIONSREQUEST,
  '__module__' : 'mbed_rpc_pb2'
  # @@protoc_insertion_point(class_scope:mbed.rpc.ListFunctionsRequest)
  })
_sym_db.RegisterMessage(ListFunctionsRequest)

ListFunctionsResponse = _reflection.GeneratedProtocolMessageType('ListFunctionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTFUNCTIONSRESPONSE,
  '__module__' : 'mbed_rpc_pb2'
  # @@protoc_insertion_point(class_scope:mbed.rpc.ListFunctionsResponse)
  })
_sym_db.RegisterMessage(ListFunctionsResponse)


_HEADER.fields_by_name['msgId']._options = None
_HEADER.fields_by_name['subId']._options = None
_HEADER.fields_by_name['seqId']._options = None
# @@protoc_insertion_point(module_scope)
