/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "mbed_rpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mbed_rpc_Header, mbed_rpc_Header, AUTO)


PB_BIND(mbed_rpc_BaseMessage, mbed_rpc_BaseMessage, AUTO)


PB_BIND(mbed_rpc_Ping, mbed_rpc_Ping, AUTO)


PB_BIND(mbed_rpc_ListFunctionsRequest, mbed_rpc_ListFunctionsRequest, AUTO)


PB_BIND(mbed_rpc_ListFunctionsResponse, mbed_rpc_ListFunctionsResponse, AUTO)







