# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mbed_rpc.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0embed_rpc.proto\x12\x08mbed.rpc\x1a\x0cnanopb.proto\"\x8b\x01\n\x06Header\x12\x12\n\x03\x63rc\x18\x01 \x02(\rB\x05\x92?\x02\x38\x10\x12\x13\n\x04size\x18\x02 \x02(\rB\x05\x92?\x02\x38\x10\x12\x16\n\x07version\x18\x03 \x02(\rB\x05\x92?\x02\x38\x08\x12\x14\n\x05seqId\x18\x04 \x02(\rB\x05\x92?\x02\x38\x08\x12\x14\n\x05msgId\x18\x05 \x02(\rB\x05\x92?\x02\x38\x08\x12\x14\n\x05svcId\x18\x06 \x02(\rB\x05\x92?\x02\x38\x08\"/\n\x0b\x42\x61seMessage\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\"l\n\x05\x45rror\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\x12)\n\x05\x65rror\x18\x02 \x02(\x0e\x32\x13.mbed.rpc.ErrorCodeB\x05\x92?\x02\x38\x08\x12\x16\n\x06\x64\x65tail\x18\x03 \x02(\x0c\x42\x06\x92?\x03\x08\x80\x02\"(\n\x04Ping\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\"8\n\x14ListFunctionsRequest\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\"L\n\x15ListFunctionsResponse\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\x12\x11\n\tfunctions\x18\x02 \x03(\t*\'\n\x0fProtocolVersion\x12\x14\n\x10RPC_PROTOCOL_VER\x10\x01*\xee\x01\n\tErrorCode\x12\x10\n\x0c\x45RR_NO_ERROR\x10\x00\x12\x11\n\rERR_SVC_ASYNC\x10\x01\x12\x10\n\x0c\x45RR_SVC_BUSY\x10\x02\x12\x0f\n\x0b\x45RR_RPC_VER\x10\x03\x12\x0f\n\x0b\x45RR_MSG_VER\x10\x04\x12\x10\n\x0c\x45RR_MSG_SIZE\x10\x05\x12\x0f\n\x0b\x45RR_MSG_CRC\x10\x06\x12\x12\n\x0e\x45RR_MSG_DECODE\x10\x07\x12\x15\n\x11\x45RR_SVC_NOT_FOUND\x10\x08\x12\x15\n\x11\x45RR_MSG_NOT_FOUND\x10\t\x12\x0f\n\x0b\x45RR_SVC_MSG\x10\n\x12\x12\n\rERR_MAX_ERROR\x10\xff\x01*\x1e\n\x0e\x42uiltinService\x12\x0c\n\x08SVC_PING\x10\x00*;\n\x0e\x42uiltinMessage\x12\x0c\n\x08MSG_NULL\x10\x00\x12\r\n\tMSG_ERROR\x10\x01\x12\x0c\n\x08MSG_PING\x10\x02*@\n\x15\x42uiltinMessageVersion\x12\x11\n\rMSG_VER_ERROR\x10\x00\x12\x10\n\x0cMSG_VER_PING\x10\x00\x1a\x02\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mbed_rpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BUILTINMESSAGEVERSION']._options = None
  _globals['_BUILTINMESSAGEVERSION']._serialized_options = b'\020\001'
  _globals['_HEADER'].fields_by_name['crc']._options = None
  _globals['_HEADER'].fields_by_name['crc']._serialized_options = b'\222?\0028\020'
  _globals['_HEADER'].fields_by_name['size']._options = None
  _globals['_HEADER'].fields_by_name['size']._serialized_options = b'\222?\0028\020'
  _globals['_HEADER'].fields_by_name['version']._options = None
  _globals['_HEADER'].fields_by_name['version']._serialized_options = b'\222?\0028\010'
  _globals['_HEADER'].fields_by_name['seqId']._options = None
  _globals['_HEADER'].fields_by_name['seqId']._serialized_options = b'\222?\0028\010'
  _globals['_HEADER'].fields_by_name['msgId']._options = None
  _globals['_HEADER'].fields_by_name['msgId']._serialized_options = b'\222?\0028\010'
  _globals['_HEADER'].fields_by_name['svcId']._options = None
  _globals['_HEADER'].fields_by_name['svcId']._serialized_options = b'\222?\0028\010'
  _globals['_ERROR'].fields_by_name['error']._options = None
  _globals['_ERROR'].fields_by_name['error']._serialized_options = b'\222?\0028\010'
  _globals['_ERROR'].fields_by_name['detail']._options = None
  _globals['_ERROR'].fields_by_name['detail']._serialized_options = b'\222?\003\010\200\002'
  _globals['_PROTOCOLVERSION']._serialized_start=521
  _globals['_PROTOCOLVERSION']._serialized_end=560
  _globals['_ERRORCODE']._serialized_start=563
  _globals['_ERRORCODE']._serialized_end=801
  _globals['_BUILTINSERVICE']._serialized_start=803
  _globals['_BUILTINSERVICE']._serialized_end=833
  _globals['_BUILTINMESSAGE']._serialized_start=835
  _globals['_BUILTINMESSAGE']._serialized_end=894
  _globals['_BUILTINMESSAGEVERSION']._serialized_start=896
  _globals['_BUILTINMESSAGEVERSION']._serialized_end=960
  _globals['_HEADER']._serialized_start=43
  _globals['_HEADER']._serialized_end=182
  _globals['_BASEMESSAGE']._serialized_start=184
  _globals['_BASEMESSAGE']._serialized_end=231
  _globals['_ERROR']._serialized_start=233
  _globals['_ERROR']._serialized_end=341
  _globals['_PING']._serialized_start=343
  _globals['_PING']._serialized_end=383
  _globals['_LISTFUNCTIONSREQUEST']._serialized_start=385
  _globals['_LISTFUNCTIONSREQUEST']._serialized_end=441
  _globals['_LISTFUNCTIONSRESPONSE']._serialized_start=443
  _globals['_LISTFUNCTIONSRESPONSE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
