"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ProtocolVersion:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ProtocolVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ProtocolVersion.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RPC_PROTOCOL_VER: _ProtocolVersion.ValueType  # 1

class ProtocolVersion(_ProtocolVersion, metaclass=_ProtocolVersionEnumTypeWrapper): ...

RPC_PROTOCOL_VER: ProtocolVersion.ValueType  # 1
global___ProtocolVersion = ProtocolVersion

class _ErrorCode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERR_NO_ERROR: _ErrorCode.ValueType  # 0
    """No error occurred"""
    ERR_SVC_ASYNC: _ErrorCode.ValueType  # 1
    """Used to indicate that the service is processing the request asynchronously without error so far"""
    ERR_SVC_BUSY: _ErrorCode.ValueType  # 2
    """Service is busy and cannot process the request"""
    ERR_RPC_VER: _ErrorCode.ValueType  # 3
    """RPC protocol version mismatch"""
    ERR_MSG_VER: _ErrorCode.ValueType  # 4
    """Message version mismatch"""
    ERR_MSG_SIZE: _ErrorCode.ValueType  # 5
    """Message size is incorrect"""
    ERR_MSG_CRC: _ErrorCode.ValueType  # 6
    """Message CRC is incorrect"""
    ERR_MSG_DECODE: _ErrorCode.ValueType  # 7
    """Message failed to decode"""
    ERR_SVC_NOT_FOUND: _ErrorCode.ValueType  # 8
    """Service not found"""
    ERR_MSG_NOT_FOUND: _ErrorCode.ValueType  # 9
    """Message not found"""
    ERR_SVC_MSG: _ErrorCode.ValueType  # 10
    """Service does not support the message"""
    ERR_SVC_FAILED: _ErrorCode.ValueType  # 11
    """Service failed to process the message"""
    ERR_SVC_NO_RSP: _ErrorCode.ValueType  # 12
    """Service has no response to the message"""
    ERR_MAX_ERROR: _ErrorCode.ValueType  # 255
    """Maximum error value"""

class ErrorCode(_ErrorCode, metaclass=_ErrorCodeEnumTypeWrapper): ...

ERR_NO_ERROR: ErrorCode.ValueType  # 0
"""No error occurred"""
ERR_SVC_ASYNC: ErrorCode.ValueType  # 1
"""Used to indicate that the service is processing the request asynchronously without error so far"""
ERR_SVC_BUSY: ErrorCode.ValueType  # 2
"""Service is busy and cannot process the request"""
ERR_RPC_VER: ErrorCode.ValueType  # 3
"""RPC protocol version mismatch"""
ERR_MSG_VER: ErrorCode.ValueType  # 4
"""Message version mismatch"""
ERR_MSG_SIZE: ErrorCode.ValueType  # 5
"""Message size is incorrect"""
ERR_MSG_CRC: ErrorCode.ValueType  # 6
"""Message CRC is incorrect"""
ERR_MSG_DECODE: ErrorCode.ValueType  # 7
"""Message failed to decode"""
ERR_SVC_NOT_FOUND: ErrorCode.ValueType  # 8
"""Service not found"""
ERR_MSG_NOT_FOUND: ErrorCode.ValueType  # 9
"""Message not found"""
ERR_SVC_MSG: ErrorCode.ValueType  # 10
"""Service does not support the message"""
ERR_SVC_FAILED: ErrorCode.ValueType  # 11
"""Service failed to process the message"""
ERR_SVC_NO_RSP: ErrorCode.ValueType  # 12
"""Service has no response to the message"""
ERR_MAX_ERROR: ErrorCode.ValueType  # 255
"""Maximum error value"""
global___ErrorCode = ErrorCode

class _BuiltinService:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BuiltinServiceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BuiltinService.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SVC_PING: _BuiltinService.ValueType  # 0
    """Accepts ping requests from clients"""
    SVC_TEST_ERROR: _BuiltinService.ValueType  # 1
    """Test error handling"""
    SVC_NOTIFY_TIME_ELAPSED: _BuiltinService.ValueType  # 2
    """Notify caller of elapsed system time"""
    SVC_LOGGER_ERASE: _BuiltinService.ValueType  # 3
    """Logger service to erase logs"""
    SVC_LOGGER_READ: _BuiltinService.ValueType  # 4
    """Logger service to read logs"""
    SVC_LOGGER_WRITE: _BuiltinService.ValueType  # 5
    """Logger service to write logs"""

class BuiltinService(_BuiltinService, metaclass=_BuiltinServiceEnumTypeWrapper): ...

SVC_PING: BuiltinService.ValueType  # 0
"""Accepts ping requests from clients"""
SVC_TEST_ERROR: BuiltinService.ValueType  # 1
"""Test error handling"""
SVC_NOTIFY_TIME_ELAPSED: BuiltinService.ValueType  # 2
"""Notify caller of elapsed system time"""
SVC_LOGGER_ERASE: BuiltinService.ValueType  # 3
"""Logger service to erase logs"""
SVC_LOGGER_READ: BuiltinService.ValueType  # 4
"""Logger service to read logs"""
SVC_LOGGER_WRITE: BuiltinService.ValueType  # 5
"""Logger service to write logs"""
global___BuiltinService = BuiltinService

class _BuiltinMessage:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BuiltinMessageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BuiltinMessage.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MSG_NULL: _BuiltinMessage.ValueType  # 0
    MSG_ERROR: _BuiltinMessage.ValueType  # 1
    MSG_PING: _BuiltinMessage.ValueType  # 2
    MSG_ACK_NACK: _BuiltinMessage.ValueType  # 3
    MSG_TICK: _BuiltinMessage.ValueType  # 4
    MSG_CONSOLE: _BuiltinMessage.ValueType  # 5
    MSG_SYSTEM_INFO: _BuiltinMessage.ValueType  # 6
    MSG_NOTIFY_TIME_ELAPSED_REQ: _BuiltinMessage.ValueType  # 7
    MSG_NOTIFY_TIME_ELAPSED_RSP: _BuiltinMessage.ValueType  # 8
    MSG_LOGGER_ERASE_REQ: _BuiltinMessage.ValueType  # 9
    MSG_LOGGER_ERASE_RSP: _BuiltinMessage.ValueType  # 10
    MSG_LOGGER_READ_REQ: _BuiltinMessage.ValueType  # 11
    MSG_LOGGER_READ_RSP: _BuiltinMessage.ValueType  # 12
    MSG_LOGGER_READ_STREAM_RSP: _BuiltinMessage.ValueType  # 13
    MSG_LOGGER_WRITE_REQ: _BuiltinMessage.ValueType  # 14
    MSG_LOGGER_WRITE_RSP: _BuiltinMessage.ValueType  # 15

class BuiltinMessage(_BuiltinMessage, metaclass=_BuiltinMessageEnumTypeWrapper): ...

MSG_NULL: BuiltinMessage.ValueType  # 0
MSG_ERROR: BuiltinMessage.ValueType  # 1
MSG_PING: BuiltinMessage.ValueType  # 2
MSG_ACK_NACK: BuiltinMessage.ValueType  # 3
MSG_TICK: BuiltinMessage.ValueType  # 4
MSG_CONSOLE: BuiltinMessage.ValueType  # 5
MSG_SYSTEM_INFO: BuiltinMessage.ValueType  # 6
MSG_NOTIFY_TIME_ELAPSED_REQ: BuiltinMessage.ValueType  # 7
MSG_NOTIFY_TIME_ELAPSED_RSP: BuiltinMessage.ValueType  # 8
MSG_LOGGER_ERASE_REQ: BuiltinMessage.ValueType  # 9
MSG_LOGGER_ERASE_RSP: BuiltinMessage.ValueType  # 10
MSG_LOGGER_READ_REQ: BuiltinMessage.ValueType  # 11
MSG_LOGGER_READ_RSP: BuiltinMessage.ValueType  # 12
MSG_LOGGER_READ_STREAM_RSP: BuiltinMessage.ValueType  # 13
MSG_LOGGER_WRITE_REQ: BuiltinMessage.ValueType  # 14
MSG_LOGGER_WRITE_RSP: BuiltinMessage.ValueType  # 15
global___BuiltinMessage = BuiltinMessage

class _BuiltinMessageVersion:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BuiltinMessageVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BuiltinMessageVersion.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MSG_VER_NULL: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_ERROR: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_PING: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_ACK_NACK: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_TICK: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_CONSOLE: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_SYSTEM_INFO: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_NOTIFY_TIME_ELAPSED_REQ: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_NOTIFY_TIME_ELAPSED_RSP: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_LOGGER_ERASE_REQ: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_LOGGER_ERASE_RSP: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_LOGGER_READ_REQ: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_LOGGER_READ_RSP: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_LOGGER_READ_STREAM_RSP: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_LOGGER_WRITE_REQ: _BuiltinMessageVersion.ValueType  # 0
    MSG_VER_LOGGER_WRITE_RSP: _BuiltinMessageVersion.ValueType  # 0

class BuiltinMessageVersion(_BuiltinMessageVersion, metaclass=_BuiltinMessageVersionEnumTypeWrapper): ...

MSG_VER_NULL: BuiltinMessageVersion.ValueType  # 0
MSG_VER_ERROR: BuiltinMessageVersion.ValueType  # 0
MSG_VER_PING: BuiltinMessageVersion.ValueType  # 0
MSG_VER_ACK_NACK: BuiltinMessageVersion.ValueType  # 0
MSG_VER_TICK: BuiltinMessageVersion.ValueType  # 0
MSG_VER_CONSOLE: BuiltinMessageVersion.ValueType  # 0
MSG_VER_SYSTEM_INFO: BuiltinMessageVersion.ValueType  # 0
MSG_VER_NOTIFY_TIME_ELAPSED_REQ: BuiltinMessageVersion.ValueType  # 0
MSG_VER_NOTIFY_TIME_ELAPSED_RSP: BuiltinMessageVersion.ValueType  # 0
MSG_VER_LOGGER_ERASE_REQ: BuiltinMessageVersion.ValueType  # 0
MSG_VER_LOGGER_ERASE_RSP: BuiltinMessageVersion.ValueType  # 0
MSG_VER_LOGGER_READ_REQ: BuiltinMessageVersion.ValueType  # 0
MSG_VER_LOGGER_READ_RSP: BuiltinMessageVersion.ValueType  # 0
MSG_VER_LOGGER_READ_STREAM_RSP: BuiltinMessageVersion.ValueType  # 0
MSG_VER_LOGGER_WRITE_REQ: BuiltinMessageVersion.ValueType  # 0
MSG_VER_LOGGER_WRITE_RSP: BuiltinMessageVersion.ValueType  # 0
global___BuiltinMessageVersion = BuiltinMessageVersion

@typing.final
class Header(google.protobuf.message.Message):
    """Core message header common to all types. Each functional message type **must**
    have this first in their list of declarations.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    SEQID_FIELD_NUMBER: builtins.int
    MSGID_FIELD_NUMBER: builtins.int
    SVCID_FIELD_NUMBER: builtins.int
    version: builtins.int
    """Version of this message."""
    seqId: builtins.int
    """Sequence ID for the message transaction"""
    msgId: builtins.int
    """Root message identifier"""
    svcId: builtins.int
    """Service identifier the message is for"""
    def __init__(
        self,
        *,
        version: builtins.int | None = ...,
        seqId: builtins.int | None = ...,
        msgId: builtins.int | None = ...,
        svcId: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["msgId", b"msgId", "seqId", b"seqId", "svcId", b"svcId", "version", b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["msgId", b"msgId", "seqId", b"seqId", "svcId", b"svcId", "version", b"version"]) -> None: ...

global___Header = Header

@typing.final
class BaseMessage(google.protobuf.message.Message):
    """Root type that parsers can use to peek at messages and figure out what type the full message is."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header"]) -> None: ...

global___BaseMessage = BaseMessage

@typing.final
class NullMessage(google.protobuf.message.Message):
    """Simple empty message type"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header"]) -> None: ...

global___NullMessage = NullMessage

@typing.final
class ErrorMessage(google.protobuf.message.Message):
    """Message type for error responses."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    DETAIL_FIELD_NUMBER: builtins.int
    error: global___ErrorCode.ValueType
    detail: builtins.bytes
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        error: global___ErrorCode.ValueType | None = ...,
        detail: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["detail", b"detail", "error", b"error", "header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["detail", b"detail", "error", b"error", "header", b"header"]) -> None: ...

global___ErrorMessage = ErrorMessage

@typing.final
class AckNackMessage(google.protobuf.message.Message):
    """Generic ACK or NACK to a previous message, with optional data payload"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    ACKNOWLEDGE_FIELD_NUMBER: builtins.int
    STATUS_CODE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    acknowledge: builtins.bool
    """True if this is an ACK, false if it's a NACK"""
    status_code: global___ErrorCode.ValueType
    """Optional error code for the ACK/NACK"""
    data: builtins.bytes
    """Optional data payload for small responses"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        acknowledge: builtins.bool | None = ...,
        status_code: global___ErrorCode.ValueType | None = ...,
        data: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["acknowledge", b"acknowledge", "data", b"data", "header", b"header", "status_code", b"status_code"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["acknowledge", b"acknowledge", "data", b"data", "header", b"header", "status_code", b"status_code"]) -> None: ...

global___AckNackMessage = AckNackMessage

@typing.final
class TickMessage(google.protobuf.message.Message):
    """Advertise the current system tick time"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    TICK_FIELD_NUMBER: builtins.int
    tick: builtins.int
    """System time in milliseconds"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        tick: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "tick", b"tick"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "tick", b"tick"]) -> None: ...

global___TickMessage = TickMessage

@typing.final
class ConsoleMessage(google.protobuf.message.Message):
    """Stream console messages in real time"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    THIS_FRAME_FIELD_NUMBER: builtins.int
    TOTAL_FRAMES_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    this_frame: builtins.int
    """Which frame is this?"""
    total_frames: builtins.int
    """How many frames are there?"""
    data: builtins.bytes
    """Data payload"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        this_frame: builtins.int | None = ...,
        total_frames: builtins.int | None = ...,
        data: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "header", b"header", "this_frame", b"this_frame", "total_frames", b"total_frames"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "header", b"header", "this_frame", b"this_frame", "total_frames", b"total_frames"]) -> None: ...

global___ConsoleMessage = ConsoleMessage

@typing.final
class SystemInfoMessage(google.protobuf.message.Message):
    """Message type for announcing some device descriptions"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    SW_VERSION_FIELD_NUMBER: builtins.int
    SERIAL_NUMBER_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    sw_version: builtins.str
    """Software version"""
    serial_number: builtins.str
    """Serial number"""
    description: builtins.str
    """Device description"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        sw_version: builtins.str | None = ...,
        serial_number: builtins.str | None = ...,
        description: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["description", b"description", "header", b"header", "serial_number", b"serial_number", "sw_version", b"sw_version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "header", b"header", "serial_number", b"serial_number", "sw_version", b"sw_version"]) -> None: ...

global___SystemInfoMessage = SystemInfoMessage

@typing.final
class PingMessage(google.protobuf.message.Message):
    """****************************************************************************
    Ping Service
    ****************************************************************************

    Simple ping message to test RPC connection.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header"]) -> None: ...

global___PingMessage = PingMessage

@typing.final
class NotifyTimeElapsedRequest(google.protobuf.message.Message):
    """****************************************************************************
    Notify Time Elapsed Service
    ****************************************************************************
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    DELAY_TIME_FIELD_NUMBER: builtins.int
    delay_time: builtins.int
    """Time to delay in ms"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        delay_time: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["delay_time", b"delay_time", "header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["delay_time", b"delay_time", "header", b"header"]) -> None: ...

global___NotifyTimeElapsedRequest = NotifyTimeElapsedRequest

@typing.final
class NotifyTimeElapsedResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    ELAPSED_TIME_FIELD_NUMBER: builtins.int
    elapsed_time: builtins.int
    """Time elapsed in ms"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        elapsed_time: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["elapsed_time", b"elapsed_time", "header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["elapsed_time", b"elapsed_time", "header", b"header"]) -> None: ...

global___NotifyTimeElapsedResponse = NotifyTimeElapsedResponse

@typing.final
class LoggerEraseRequest(google.protobuf.message.Message):
    """****************************************************************************
    Logger Service
    ****************************************************************************
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    WHICH_FIELD_NUMBER: builtins.int
    which: builtins.int
    """Which log to erase"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        which: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "which", b"which"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "which", b"which"]) -> None: ...

global___LoggerEraseRequest = LoggerEraseRequest

@typing.final
class LoggerEraseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """True if the log was erased successfully"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        success: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "success", b"success"]) -> None: ...

global___LoggerEraseResponse = LoggerEraseResponse

@typing.final
class LoggerReadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    WHICH_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    which: builtins.int
    """Which log to read"""
    direction: builtins.bool
    """True for forward (FIFO), false for backward (LIFO)"""
    count: builtins.int
    """Number of entries to read, -1 for all"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        which: builtins.int | None = ...,
        direction: builtins.bool | None = ...,
        count: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["count", b"count", "direction", b"direction", "header", b"header", "which", b"which"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["count", b"count", "direction", b"direction", "header", b"header", "which", b"which"]) -> None: ...

global___LoggerReadRequest = LoggerReadRequest

@typing.final
class LoggerReadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """True if data is available"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        success: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "success", b"success"]) -> None: ...

global___LoggerReadResponse = LoggerReadResponse

@typing.final
class LoggerReadStreamResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    index: builtins.int
    """Index of the log entry"""
    data: builtins.bytes
    """Data payload"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        index: builtins.int | None = ...,
        data: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "header", b"header", "index", b"index"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "header", b"header", "index", b"index"]) -> None: ...

global___LoggerReadStreamResponse = LoggerReadStreamResponse

@typing.final
class LoggerWriteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    WHICH_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    which: builtins.int
    """Which log to write"""
    data: builtins.bytes
    """Data payload"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        which: builtins.int | None = ...,
        data: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "header", b"header", "which", b"which"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "header", b"header", "which", b"which"]) -> None: ...

global___LoggerWriteRequest = LoggerWriteRequest

@typing.final
class LoggerWriteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """True if the data was logged successfully"""
    @property
    def header(self) -> global___Header: ...
    def __init__(
        self,
        *,
        header: global___Header | None = ...,
        success: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "success", b"success"]) -> None: ...

global___LoggerWriteResponse = LoggerWriteResponse
